export 'package:widgets_app/screens/animated/animated_screen.dart';
export 'package:widgets_app/screens/app_tutorial/app_tutorial_screen.dart';
export 'package:widgets_app/screens/buttons/buttons_screen.dart';
export 'package:widgets_app/screens/cards/cards_screen.dart';
export 'package:widgets_app/screens/home/home_screen.dart';
export 'package:widgets_app/screens/infinite_scroll/infinite_scroll_screen.dart';
export 'package:widgets_app/screens/progress/progress_screen.dart';
export 'package:widgets_app/screens/snackbar/snackbar_screen.dart';
export 'package:widgets_app/screens/ui_controls/ui_controls_screen.dart';
